### ISSUE TITLE
Ajout d'un lien

### ISSUE THREAD

**Issue by civodul999** [stephrobert/awesome-french-devops#135]
Hello Stéphane,

je suis tombé sur ce site pour avoir des informations sur Kubernetes : 

[Devsecops](https://devopssec.fr/category/apprendre-kubernetes)

A rajouter dans la section 2.1.4 si cela te convient.

**Comment by stephrobert** [comment]
Je dois en rajouter bcp mais pas assez de temps

Le jeu. 26 janv. 2023, 20:34, civodul999 ***@***.***> a
écrit :
