### ISSUE TITLE
Suggest - reorganize README

### ISSUE THREAD

**Issue by jeanphibaconnais** [stephrobert/awesome-french-devops#4]
Le readme est assez conséquente, est-ce que ce ne vaudrait pas le coup de découper ?

+ mentionner la partie contribution en bas du readme 😄

**Comment by stephrobert** [comment]
Bonne idée je regarde comment le mettre en oeuvre. Et simplifier la table des matières aussi

**Comment by jeanphibaconnais** [comment]
On peut le faire avec des fichiers par chapitre.
